### ISSUE TITLE
Post refresh

### ISSUE THREAD

**Issue by solleer** [Level-2/Config-Router-ModuleJson#1]
How do you stop page refreshes from resubmitting the post request with out redirection since the post request still has a view?

**Comment by TomBZombie** [comment]
The same as every framework: Redirect. The view will perform a redirect on success.

**Comment by solleer** [comment]
If I use a true/false variable to have the view display a success message would it be a session variable so it carries over to the next page

**Comment by TomBZombie** [comment]
It depends on the message: "Your message has been posted" can easily go on its own page that is redirected to.

**Comment by solleer** [comment]
If we want to display a message not on its own page would you use a get variable. A session variable would be preferred but I can't think of a good way to do that without compromising reusability.
